#include "backends/horizon_module_emitter.h"

#include "utils/check.h"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <vector>

namespace edge_fm {

namespace {

std::string py_path_literal(const std::string& path) {
    return nlohmann::json(path).dump();
}

std::string py_json_expr(const nlohmann::json& json) {
    return "json.loads(r'''"
        + json.dump(2)
        + "''')";
}

std::string horizon_module_source(
    const std::string& model_name,
    const nlohmann::json& model_config,
    const std::string& prefill_model_path,
    const std::string& decode_model_path,
    const nlohmann::json& graph_tuning,
    const nlohmann::json& lowering)
{
    const int32_t hidden_size = model_config.value("hidden_size", 0);
    const int32_t intermediate_size = model_config.value("intermediate_size", 0);
    const int32_t num_attention_heads = model_config.value("num_attention_heads", 0);
    const int32_t num_key_value_heads = model_config.value("num_key_value_heads", num_attention_heads);
    const int32_t head_dim = (num_attention_heads > 0) ? (hidden_size / num_attention_heads) : 0;
    const int32_t vocab_size = model_config.value("vocab_size", 0);
    const bool tie_word_embeddings = model_config.value("tie_word_embeddings", false);
    const float rope_theta = model_config.value("rope_theta", 1000000.0f);
    const bool uses_mrope = graph_tuning.value(
        "uses_mrope",
        model_config.contains("rope_scaling") &&
            model_config["rope_scaling"].is_object() &&
            model_config["rope_scaling"].value(
                "type",
                model_config["rope_scaling"].value("rope_type", std::string(""))) == "mrope");
    const int32_t num_layers = model_config.value("num_hidden_layers", 0);
    check<ConfigurationError>(num_layers > 0, "Horizon module emitter requires num_hidden_layers > 0");

    std::ostringstream oss;
    oss
        << "# Auto-generated by EdgeFM for Horizon backend.\n"
        << "from __future__ import annotations\n\n"
        << "import json\n"
        << "from pathlib import Path\n"
        << "from typing import Dict, Iterable, List, Optional, Sequence, Tuple\n\n"
        << "import torch\n"
        << "import torch.nn as nn\n"
        << "import torch.nn.functional as F\n"
        << "from safetensors.torch import load_file\n\n"
        << "MODEL_NAME = " << py_path_literal(model_name) << "\n"
        << "MODEL_CONFIG = " << py_json_expr(model_config) << "\n"
        << "EDGEFM_GRAPH_TUNING = " << py_json_expr(graph_tuning) << "\n"
        << "EDGEFM_HORIZON_LOWERING = " << py_json_expr(lowering) << "\n"
        << "PREFILL_MODEL_PATH = Path(" << py_path_literal(prefill_model_path) << ")\n"
        << "DECODE_MODEL_PATH = Path(" << py_path_literal(decode_model_path) << ")\n\n"
        << "def _normalize_weight_key(key: str) -> str:\n"
        << "    if key.startswith(\"model.model.\"):\n"
        << "        return \"model.\" + key[len(\"model.model.\"):]\n"
        << "    return key\n\n"
        << "def _collect_safetensors_files(model_dir: Path) -> List[Path]:\n"
        << "    single = model_dir / \"model.safetensors\"\n"
        << "    if single.exists():\n"
        << "        return [single]\n"
        << "    files = sorted(model_dir.glob(\"model-*.safetensors\"))\n"
        << "    if files:\n"
        << "        return files\n"
        << "    raise FileNotFoundError(f\"No safetensors files found under {model_dir}\")\n\n"
        << "def load_edgefm_state_dict(model_dir: Path) -> Dict[str, torch.Tensor]:\n"
        << "    state: Dict[str, torch.Tensor] = {}\n"
        << "    for file_path in _collect_safetensors_files(model_dir):\n"
        << "        for name, tensor in load_file(str(file_path)).items():\n"
        << "            state[_normalize_weight_key(name)] = tensor\n"
        << "    return state\n\n"
        << "class EdgeFMRMSNorm(nn.Module):\n"
        << "    def __init__(self, hidden_size: int, eps: float = 1e-6):\n"
        << "        super().__init__()\n"
        << "        self.weight = nn.Parameter(torch.ones(hidden_size))\n"
        << "        self.eps = eps\n\n"
        << "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
        << "        variance = x.pow(2).mean(dim=-1, keepdim=True)\n"
        << "        x = x * torch.rsqrt(variance + self.eps)\n"
        << "        return x * self.weight\n\n"
        << "    def load_hf(self, state_dict: Dict[str, torch.Tensor], key: str) -> None:\n"
        << "        with torch.no_grad():\n"
        << "            self.weight.copy_(state_dict[key])\n\n"
        << "class EdgeFMFusedQKVProjection(nn.Module):\n"
        << "    def __init__(self, hidden_size: int, num_attention_heads: int, num_key_value_heads: int, head_dim: int):\n"
        << "        super().__init__()\n"
        << "        self.num_attention_heads = num_attention_heads\n"
        << "        self.num_key_value_heads = num_key_value_heads\n"
        << "        self.head_dim = head_dim\n"
        << "        total = num_attention_heads * head_dim + 2 * num_key_value_heads * head_dim\n"
        << "        self.linear = nn.Linear(hidden_size, total, bias=False)\n\n"
        << "    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n"
        << "        q_dim = self.num_attention_heads * self.head_dim\n"
        << "        kv_dim = self.num_key_value_heads * self.head_dim\n"
        << "        qkv = self.linear(x)\n"
        << "        q, k, v = torch.split(qkv, [q_dim, kv_dim, kv_dim], dim=-1)\n"
        << "        bsz, seq_len, _ = x.shape\n"
        << "        q = q.view(bsz, seq_len, self.num_attention_heads, self.head_dim)\n"
        << "        k = k.view(bsz, seq_len, self.num_key_value_heads, self.head_dim)\n"
        << "        v = v.view(bsz, seq_len, self.num_key_value_heads, self.head_dim)\n"
        << "        return q, k, v\n\n"
        << "    def load_hf(self, state_dict: Dict[str, torch.Tensor], prefix: str) -> None:\n"
        << "        q_w = state_dict[f\"{prefix}.q_proj.weight\"]\n"
        << "        k_w = state_dict[f\"{prefix}.k_proj.weight\"]\n"
        << "        v_w = state_dict[f\"{prefix}.v_proj.weight\"]\n"
        << "        with torch.no_grad():\n"
        << "            self.linear.weight.copy_(torch.cat([q_w, k_w, v_w], dim=0))\n\n"
        << "class EdgeFMGateUpProjection(nn.Module):\n"
        << "    def __init__(self, hidden_size: int, intermediate_size: int):\n"
        << "        super().__init__()\n"
        << "        self.intermediate_size = intermediate_size\n"
        << "        self.linear = nn.Linear(hidden_size, 2 * intermediate_size, bias=False)\n\n"
        << "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
        << "        return self.linear(x)\n\n"
        << "    def load_hf(self, state_dict: Dict[str, torch.Tensor], prefix: str) -> None:\n"
        << "        gate_w = state_dict[f\"{prefix}.gate_proj.weight\"]\n"
        << "        up_w = state_dict[f\"{prefix}.up_proj.weight\"]\n"
        << "        with torch.no_grad():\n"
        << "            self.linear.weight.copy_(torch.cat([gate_w, up_w], dim=0))\n\n"
        << "class EdgeFMSiLUAndMul(nn.Module):\n"
        << "    def __init__(self, intermediate_size: int):\n"
        << "        super().__init__()\n"
        << "        self.intermediate_size = intermediate_size\n\n"
        << "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
        << "        gate, up = torch.split(x, [self.intermediate_size, self.intermediate_size], dim=-1)\n"
        << "        return F.silu(gate) * up\n\n"
        << "def _rotate_half(x: torch.Tensor) -> torch.Tensor:\n"
        << "    x1 = x[..., ::2]\n"
        << "    x2 = x[..., 1::2]\n"
        << "    return torch.stack((-x2, x1), dim=-1).flatten(-2)\n\n"
        << "def _apply_rotary(q: torch.Tensor, k: torch.Tensor, position_ids: Optional[torch.Tensor], rope_theta: float, use_mrope: bool) -> Tuple[torch.Tensor, torch.Tensor]:\n"
        << "    if position_ids is None or use_mrope:\n"
        << "        return q, k\n"
        << "    if position_ids.dim() == 1:\n"
        << "        position_ids = position_ids.unsqueeze(0)\n"
        << "    if position_ids.dim() > 2:\n"
        << "        position_ids = position_ids.reshape(position_ids.shape[0], -1)\n"
        << "    rotary_dim = q.shape[-1]\n"
        << "    inv_freq = 1.0 / (rope_theta ** (torch.arange(0, rotary_dim, 2, device=q.device, dtype=q.dtype) / rotary_dim))\n"
        << "    freqs = torch.einsum(\"bs,d->bsd\", position_ids.to(q.dtype), inv_freq)\n"
        << "    emb = torch.cat([freqs, freqs], dim=-1).unsqueeze(2)\n"
        << "    cos = emb.cos()\n"
        << "    sin = emb.sin()\n"
        << "    q = (q * cos) + (_rotate_half(q) * sin)\n"
        << "    k = (k * cos) + (_rotate_half(k) * sin)\n"
        << "    return q, k\n\n"
        << "class EdgeFMHorizonAttention(nn.Module):\n"
        << "    def __init__(self, num_attention_heads: int, num_key_value_heads: int, head_dim: int, rope_theta: float, use_mrope: bool):\n"
        << "        super().__init__()\n"
        << "        self.num_attention_heads = num_attention_heads\n"
        << "        self.num_key_value_heads = num_key_value_heads\n"
        << "        self.head_dim = head_dim\n"
        << "        self.rope_theta = rope_theta\n"
        << "        self.use_mrope = use_mrope\n\n"
        << "    def forward(\n"
        << "        self,\n"
        << "        q: torch.Tensor,\n"
        << "        k: torch.Tensor,\n"
        << "        v: torch.Tensor,\n"
        << "        kv_cache: Optional[Tuple[torch.Tensor, torch.Tensor]] = None,\n"
        << "        position_ids: Optional[torch.Tensor] = None,\n"
        << "    ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:\n"
        << "        q, k = _apply_rotary(q, k, position_ids, self.rope_theta, self.use_mrope)\n"
        << "        present_k = k\n"
        << "        present_v = v\n"
        << "        if kv_cache is not None:\n"
        << "            past_k, past_v = kv_cache\n"
        << "            if past_k is not None and past_v is not None:\n"
        << "                present_k = torch.cat([past_k, k], dim=1)\n"
        << "                present_v = torch.cat([past_v, v], dim=1)\n"
        << "        attn_k = present_k\n"
        << "        attn_v = present_v\n"
        << "        if attn_k.shape[2] != q.shape[2]:\n"
        << "            repeat = q.shape[2] // attn_k.shape[2]\n"
        << "            attn_k = attn_k.repeat_interleave(repeat, dim=2)\n"
        << "            attn_v = attn_v.repeat_interleave(repeat, dim=2)\n"
        << "        q_t = q.transpose(1, 2)\n"
        << "        k_t = attn_k.transpose(1, 2)\n"
        << "        v_t = attn_v.transpose(1, 2)\n"
        << "        out = F.scaled_dot_product_attention(q_t, k_t, v_t, attn_mask=None, is_causal=kv_cache is None)\n"
        << "        out = out.transpose(1, 2).contiguous()\n"
        << "        bsz, seq_len, _, _ = out.shape\n"
        << "        return out.view(bsz, seq_len, -1), (present_k, present_v)\n\n"
        << "class EdgeFMDecoderLayer(nn.Module):\n"
        << "    def __init__(self, layer_id: int, hidden_size: int, intermediate_size: int, num_attention_heads: int, num_key_value_heads: int, head_dim: int, rope_theta: float, use_mrope: bool):\n"
        << "        super().__init__()\n"
        << "        self.layer_id = layer_id\n"
        << "        self.input_norm = EdgeFMRMSNorm(hidden_size)\n"
        << "        self.qkv = EdgeFMFusedQKVProjection(hidden_size, num_attention_heads, num_key_value_heads, head_dim)\n"
        << "        self.attention = EdgeFMHorizonAttention(num_attention_heads, num_key_value_heads, head_dim, rope_theta, use_mrope)\n"
        << "        self.o_proj = nn.Linear(hidden_size, hidden_size, bias=False)\n"
        << "        self.post_norm = EdgeFMRMSNorm(hidden_size)\n"
        << "        self.gate_up = EdgeFMGateUpProjection(hidden_size, intermediate_size)\n"
        << "        self.activation = EdgeFMSiLUAndMul(intermediate_size)\n"
        << "        self.down_proj = nn.Linear(intermediate_size, hidden_size, bias=False)\n\n"
        << "    def forward(self, hidden_states: torch.Tensor, kv_cache: Optional[Tuple[torch.Tensor, torch.Tensor]] = None, position_ids: Optional[torch.Tensor] = None) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:\n"
        << "        residual = hidden_states\n"
        << "        normed = self.input_norm(hidden_states)\n"
        << "        q, k, v = self.qkv(normed)\n"
        << "        attn_out, present = self.attention(q, k, v, kv_cache=kv_cache, position_ids=position_ids)\n"
        << "        hidden_states = residual + self.o_proj(attn_out)\n"
        << "        mlp_residual = hidden_states\n"
        << "        hidden_states = self.post_norm(hidden_states)\n"
        << "        hidden_states = self.gate_up(hidden_states)\n"
        << "        hidden_states = self.activation(hidden_states)\n"
        << "        hidden_states = self.down_proj(hidden_states)\n"
        << "        hidden_states = mlp_residual + hidden_states\n"
        << "        return hidden_states, present\n\n"
        << "    def load_hf(self, state_dict: Dict[str, torch.Tensor], layer_id: int) -> None:\n"
        << "        prefix = f\"model.layers.{layer_id}\"\n"
        << "        self.input_norm.load_hf(state_dict, f\"{prefix}.input_layernorm.weight\")\n"
        << "        self.qkv.load_hf(state_dict, f\"{prefix}.self_attn\")\n"
        << "        with torch.no_grad():\n"
        << "            self.o_proj.weight.copy_(state_dict[f\"{prefix}.self_attn.o_proj.weight\"])\n"
        << "        self.post_norm.load_hf(state_dict, f\"{prefix}.post_attention_layernorm.weight\")\n"
        << "        self.gate_up.load_hf(state_dict, f\"{prefix}.mlp\")\n"
        << "        with torch.no_grad():\n"
        << "            self.down_proj.weight.copy_(state_dict[f\"{prefix}.mlp.down_proj.weight\"])\n\n"
        << "class EdgeFMHorizonModel(nn.Module):\n"
        << "    def __init__(self):\n"
        << "        super().__init__()\n"
        << "        self.hidden_size = " << hidden_size << "\n"
        << "        self.intermediate_size = " << intermediate_size << "\n"
        << "        self.num_attention_heads = " << num_attention_heads << "\n"
        << "        self.num_key_value_heads = " << num_key_value_heads << "\n"
        << "        self.head_dim = " << head_dim << "\n"
        << "        self.num_layers = " << num_layers << "\n"
        << "        self.vocab_size = " << vocab_size << "\n"
        << "        self.tie_word_embeddings = " << (tie_word_embeddings ? "True" : "False") << "\n"
        << "        self.embed_tokens = nn.Embedding(self.vocab_size, self.hidden_size)\n"
        << "        self.layers = nn.ModuleList([\n"
        << "            EdgeFMDecoderLayer(layer_id=i, hidden_size=self.hidden_size, intermediate_size=self.intermediate_size, num_attention_heads=self.num_attention_heads, num_key_value_heads=self.num_key_value_heads, head_dim=self.head_dim, rope_theta=" << rope_theta << ", use_mrope=" << (uses_mrope ? "True" : "False") << ")\n"
        << "            for i in range(self.num_layers)\n"
        << "        ])\n"
        << "        self.final_norm = EdgeFMRMSNorm(self.hidden_size)\n"
        << "        self.lm_head = nn.Linear(self.hidden_size, self.vocab_size, bias=False)\n\n"
        << "    def inject_embeddings(self, token_ids: torch.Tensor, hidden_states: torch.Tensor, embeddings: Optional[torch.Tensor], embed_token_id: int) -> torch.Tensor:\n"
        << "        if embeddings is None or embed_token_id < 0:\n"
        << "            return hidden_states\n"
        << "        mask = (token_ids >= embed_token_id) & (token_ids < embed_token_id + embeddings.shape[0])\n"
        << "        if not bool(mask.any()):\n"
        << "            return hidden_states\n"
        << "        hidden_states = hidden_states.clone()\n"
        << "        indices = (token_ids[mask] - embed_token_id).long()\n"
        << "        hidden_states[mask] = embeddings.index_select(0, indices)\n"
        << "        return hidden_states\n\n"
        << "    def forward(\n"
        << "        self,\n"
        << "        token_ids: torch.Tensor,\n"
        << "        kv_cache: Optional[Sequence[Optional[Tuple[torch.Tensor, torch.Tensor]]]] = None,\n"
        << "        position_ids: Optional[torch.Tensor] = None,\n"
        << "        embeddings: Optional[torch.Tensor] = None,\n"
        << "        embed_token_id: int = -1,\n"
        << "    ):\n"
        << "        hidden_states = self.embed_tokens(token_ids)\n"
        << "        hidden_states = self.inject_embeddings(token_ids, hidden_states, embeddings, embed_token_id)\n"
        << "        present: List[Tuple[torch.Tensor, torch.Tensor]] = []\n"
        << "        for layer_id, layer in enumerate(self.layers):\n"
        << "            layer_cache = None if kv_cache is None else kv_cache[layer_id]\n"
        << "            hidden_states, present_kv = layer(hidden_states, kv_cache=layer_cache, position_ids=position_ids)\n"
        << "            present.append(present_kv)\n"
        << "        hidden_states = self.final_norm(hidden_states)\n"
        << "        logits = self.lm_head(hidden_states)\n"
        << "        return {\"logits\": logits, \"present_kv\": tuple(present)}\n\n"
        << "    def load_edgefm_weights(self, stage: str = \"prefill\") -> \"EdgeFMHorizonModel\":\n"
        << "        model_dir = PREFILL_MODEL_PATH if stage == \"prefill\" else DECODE_MODEL_PATH\n"
        << "        state_dict = load_edgefm_state_dict(model_dir)\n"
        << "        with torch.no_grad():\n"
        << "            self.embed_tokens.weight.copy_(state_dict[\"model.embed_tokens.weight\"])\n"
        << "        for layer_id, layer in enumerate(self.layers):\n"
        << "            layer.load_hf(state_dict, layer_id)\n"
        << "        self.final_norm.load_hf(state_dict, \"model.norm.weight\")\n"
        << "        if \"lm_head.weight\" in state_dict:\n"
        << "            with torch.no_grad():\n"
        << "                self.lm_head.weight.copy_(state_dict[\"lm_head.weight\"])\n"
        << "        elif self.tie_word_embeddings:\n"
        << "            self.lm_head.weight = self.embed_tokens.weight\n"
        << "        else:\n"
        << "            raise KeyError(\"lm_head.weight not found and tie_word_embeddings is false\")\n"
        << "        return self\n\n"
        << "def build_model(stage: str = \"prefill\") -> EdgeFMHorizonModel:\n"
        << "    model = EdgeFMHorizonModel()\n"
        << "    model.load_edgefm_weights(stage=stage)\n"
        << "    model.eval()\n"
        << "    return model\n";

    return oss.str();
}

std::string smolvla_horizon_module_source(
    const nlohmann::json& model_config,
    const std::string& prefill_model_path,
    const nlohmann::json& graph_tuning,
    const nlohmann::json& lowering)
{
    const nlohmann::json horizon_rewrite = graph_tuning.value("horizon_rewrite", nlohmann::json::object());
    const std::string lerobot_root =
        horizon_rewrite.contains("smolvla") && horizon_rewrite["smolvla"].is_object()
        ? horizon_rewrite["smolvla"].value("lerobot_root", std::string("~/DATA/repos/public/lerobot"))
        : std::string("~/DATA/repos/public/lerobot");

    std::ostringstream oss;
    oss
        << "# Auto-generated by EdgeFM for Horizon SmolVLA backend.\n"
        << "from __future__ import annotations\n\n"
        << "import json\n"
        << "import os\n"
        << "import sys\n"
        << "from pathlib import Path\n"
        << "from typing import Any\n\n"
        << "import torch.nn as nn\n\n"
        << "MODEL_NAME = \"smolvla\"\n"
        << "MODEL_CONFIG = " << py_json_expr(model_config) << "\n"
        << "EDGEFM_GRAPH_TUNING = " << py_json_expr(graph_tuning) << "\n"
        << "EDGEFM_HORIZON_LOWERING = " << py_json_expr(lowering) << "\n"
        << "PREFILL_MODEL_PATH = Path(" << py_path_literal(prefill_model_path) << ")\n"
        << "LEROBOT_ROOT = Path(os.environ.get(\"EDGE_FM_LEROBOT_ROOT\", "
        << py_path_literal(lerobot_root) << ")).expanduser()\n\n"
        << "def _add_lerobot_to_path(lerobot_root: Path) -> None:\n"
        << "    src = lerobot_root / \"src\"\n"
        << "    if src.exists() and str(src) not in sys.path:\n"
        << "        sys.path.insert(0, str(src))\n\n"
        << "class EdgeFMSmolVLAHorizonModel(nn.Module):\n"
        << "    def __init__(self, stage: str = \"prefill\", load_policy: bool = True, lerobot_root: str | None = None):\n"
        << "        super().__init__()\n"
        << "        self.stage = stage\n"
        << "        self.lerobot_root = Path(lerobot_root).expanduser() if lerobot_root else LEROBOT_ROOT\n"
        << "        self.policy = None\n"
        << "        if load_policy:\n"
        << "            self.load_edgefm_weights(stage=stage)\n\n"
        << "    def load_edgefm_weights(self, stage: str = \"prefill\") -> \"EdgeFMSmolVLAHorizonModel\":\n"
        << "        del stage\n"
        << "        _add_lerobot_to_path(self.lerobot_root)\n"
        << "        from lerobot.policies.smolvla.modeling_smolvla import SmolVLAPolicy\n"
        << "        from scripts.horizon.j6m_rewrite import apply_smolvla_j6m_rewrites\n"
        << "        self.policy = SmolVLAPolicy.from_pretrained(str(PREFILL_MODEL_PATH))\n"
        << "        apply_smolvla_j6m_rewrites(self.policy, self.lerobot_root)\n"
        << "        self.policy.eval()\n"
        << "        return self\n\n"
        << "    def forward(self, *args: Any, **kwargs: Any):\n"
        << "        if self.policy is None:\n"
        << "            raise RuntimeError(\"SmolVLA policy is not loaded; call load_edgefm_weights() before compile/export\")\n"
        << "        if hasattr(self.policy, \"model\") and hasattr(self.policy.model, \"sample_actions\"):\n"
        << "            return self.policy.model.sample_actions(*args, **kwargs)\n"
        << "        return self.policy(*args, **kwargs)\n\n"
        << "def build_model(stage: str = \"prefill\", load_policy: bool | None = None, lerobot_root: str | None = None) -> EdgeFMSmolVLAHorizonModel:\n"
        << "    if load_policy is None:\n"
        << "        skip = os.environ.get(\"EDGE_FM_HORIZON_SKIP_SMOLVLA_LOAD\", \"0\").lower() in {\"1\", \"true\", \"yes\"}\n"
        << "        load_policy = not skip\n"
        << "    model = EdgeFMSmolVLAHorizonModel(stage=stage, load_policy=load_policy, lerobot_root=lerobot_root)\n"
        << "    model.eval()\n"
        << "    return model\n";

    return oss.str();
}

} // namespace

nlohmann::json HorizonModuleExport::to_json() const {
    return nlohmann::json{
        {"module_path", module_path},
        {"module_name", module_name},
        {"model_class", model_class},
        {"factory_function", factory_function},
        {"lowering", lowering},
    };
}

HorizonModuleExport emit_horizon_module(
    const std::string& model_name,
    const nlohmann::json& model_config,
    const std::string& prefill_model_path,
    const std::string& decode_model_path,
    const nlohmann::json& graph_tuning,
    const std::filesystem::path& output_dir)
{
    check<ConfigurationError>(
        model_name == "qwen2_5" || model_name == "qwen2_5_vl" || model_name == "smolvla",
        "Horizon module emitter only supports qwen2_5 / qwen2_5_vl / smolvla");
    check<ConfigurationError>(
        model_config.is_object(),
        "Horizon module emitter requires model_config");

    std::filesystem::create_directories(output_dir);

    HorizonModuleExport exported;
    exported.factory_function = "build_model";
    exported.module_path = (output_dir / "horizon_model.py").string();
    std::string source;
    if (model_name == "smolvla") {
        exported.module_name = "edgefm_horizon_smolvla_model";
        exported.model_class = "EdgeFMSmolVLAHorizonModel";
        exported.lowering = {
            {"strategy", "lerobot_smolvla_j6m_rewrite_adapter"},
            {"op_replacements", {
                {"AttentionMask", "j6m_bool_mask_with_bounded_fill"},
                {"RoPE", "j6m_explicit_sincos_fp32"},
                {"GELUTanh", "j6m_safe_piecewise_gelu_tanh"},
                {"FlowMatchingLoop", "per_step_hbm_or_bin_export_plan"},
                {"ScaleDiagnostics", "int16_range_report"},
            }},
            {"notes", nlohmann::json::array({
                "SmolVLA uses LeRobot as the Python source of truth for Horizon compilation.",
                "The generated adapter loads SmolVLAPolicy and applies scripts/horizon/j6m_rewrite.py before export.",
                "Flow-matching loop I/O mapping is prepared as diagnostics; runtime token/action loop wiring remains a later interface phase.",
            })},
        };
        source = smolvla_horizon_module_source(
            model_config,
            prefill_model_path,
            graph_tuning,
            exported.lowering);
    } else {
        exported.module_name = "edgefm_horizon_model";
        exported.model_class = "EdgeFMHorizonModel";
        exported.lowering = {
            {"strategy", "rewrite_to_torch_module"},
            {"op_replacements", {
                {"Embedding", "nn.Embedding"},
                {"RMSNorm", "EdgeFMRMSNorm"},
                {"QKVLinear", "EdgeFMFusedQKVProjection"},
                {"Attention", "EdgeFMHorizonAttention"},
                {"ResidualAdd", "python_residual_add"},
                {"Linear", "nn.Linear"},
                {"SiLUAndMul", "EdgeFMSiLUAndMul"},
                {"LMHead", "nn.Linear"},
                {"InjectEmbedding", "python_embedding_injection"},
            }},
            {"notes", nlohmann::json::array({
                "This module is generated from explicit model_name + model_config and serves as the Python source of truth for Horizon whole-graph compilation.",
                "Attention and fused projections remain explicit module boundaries so Horizon-specific tooling can replace or lower them further.",
                "Graph metadata embeds the resolved operator implementation table so backend-specific lowering can honor the chosen linear implementations later.",
            })},
        };
        source = horizon_module_source(
            model_name,
            model_config,
            prefill_model_path,
            decode_model_path.empty() ? prefill_model_path : decode_model_path,
            graph_tuning,
            exported.lowering);
    }

    std::ofstream output(exported.module_path);
    check<ConfigurationError>(
        output.is_open(),
        "Failed to write generated Horizon module: " + exported.module_path);
    output << source;
    return exported;
}

} // namespace edge_fm
